spring:
  application:
    name: payment-service
  cloud:
    config:
      enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:postgresql://${PAYMENT_DB_HOST:localhost}:${PAYMENT_DB_PORT:5432}/${PAYMENT_DB_NAME:payment_db}
    username: ${PAYMENT_DB_USERNAME:nicko}
    password: ${PAYMENT_DB_PASSWORD:nicko}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: ${PAYMENT_JWT_AUDIENCE:payment-service}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9091/realms/mobile-money-wallet}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/mobile-money-wallet/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

server:
  port: ${SERVER_PORT:8083}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

clients:
  wallet:
    url: ${CLIENTS_WALLET_URL:http://localhost:8082}

app:
  keycloak:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:mobile-money-wallet}
    payment-client-id: ${PAYMENT_WALLET_CLIENT_ID:payment-service}
    payment-client-secret: ${PAYMENT_WALLET_CLIENT_SECRET:}
  mpesa:
    base-url: ${MPESA_BASE_URL:https://sandbox.safaricom.co.ke}
    consumer-key: ${MPESA_CONSUMER_KEY:}
    consumer-secret: ${MPESA_CONSUMER_SECRET:}
    business-short-code: ${MPESA_BUSINESS_SHORT_CODE:}
    passkey: ${MPESA_PASSKEY:}
    transaction-type: ${MPESA_TRANSACTION_TYPE:CustomerPayBillOnline}
    public-base-url: ${MPESA_PUBLIC_BASE_URL:}
    callback-token: ${MPESA_CALLBACK_TOKEN:}
    callback-retry-interval-ms: ${PAYMENT_CALLBACK_RETRY_INTERVAL_MS:5000}
  kafka:
    enabled: ${KAFKA_ENABLED:false}
    outbox-poll-interval-ms: ${PAYMENT_OUTBOX_POLL_INTERVAL_MS:1000}
    topics:
      payment-events: ${PAYMENT_EVENTS_TOPIC:payment.events.v1}
